export default {
  PENCIL: 'PENCIL',
  LINE: 'LINE',
  // ELLIPSE: 'ELLIPSE',
  // ELLIPSE_FILL: 'ELLIPSE_FILL',
  // RECTANGLE: 'RECTANGLE',
  // RECTANGLE_FILL: 'RECTANGLE_FILL',
  // FILL: 'FILL'
};
