import brands from '../brands';

const brand = brands.HAMA;
const hamaBeads = [
  {brand, code: 'H01', name: 'White', type: 'regular ', color: '#eceded'},
  {brand, code: 'H02', name: 'Cream', type: 'regular ', color: '#f0e8b9'},
  {brand, code: 'H03', name: 'Yellow', type: 'regular ', color: '#f0b901'},
  {brand, code: 'H04', name: 'Orange', type: 'regular ', color: '#e64f27'},
  {brand, code: 'H05', name: 'Red', type: 'regular ', color: '#b63136'},
  {brand, code: 'H06', name: 'Pink', type: 'regular ', color: '#e1889f'},
  {brand, code: 'H07', name: 'Purple', type: 'regular ', color: '#694a82'},
  {brand, code: 'H08', name: 'Dark Blue', type: 'regular ', color: '#2C4690'},
  {brand, code: 'H09', name: 'Light Blue', type: 'regular ', color: '#305CB0'},
  {brand, code: 'H10', name: 'Green', type: 'regular ', color: '#256847'},
  {brand, code: 'H11', name: 'Light Green', type: 'regular ', color: '#49AE89'},
  {brand, code: 'H12', name: 'Brown', type: 'regular ', color: '#534137'},
  {brand, code: 'H13', name: 'Transparent Red', type: 'transparent ', color: '#C02435'},
  {brand, code: 'H16', name: 'Transparent Green', type: 'transparent ', color: '#37B876'},
  {brand, code: 'H17', name: 'Grey', type: 'regular ', color: '#83888A'},
  {brand, code: 'H18', name: 'Black', type: 'regular ', color: '#2E2F31'},
  {brand, code: 'H19', name: 'Clear', type: 'transparent ', color: '#D8D2CE'},
  {brand, code: 'H20', name: 'Reddish Brown', type: 'regular ', color: '#7F332A'},
  {brand, code: 'H21', name: 'Light Brown', type: 'regular ', color: '#A5693F'},
  {brand, code: 'H22', name: 'Dark Red', type: 'regular ', color: '#A52D36'},
  {brand, code: 'H24', name: 'Translucent Purple', type: 'transparent ', color: '#683E9A'},
  {brand, code: 'H25', name: 'Translucent Brown', type: 'transparent ', color: '#87593D'},
  {brand, code: 'H26', name: 'Flesh', type: 'regular ', color: '#DE9B90'},
  {brand, code: 'H27', name: 'Beige', type: 'regular ', color: '#DEB48B'},
  {brand, code: 'H28', name: 'Army', type: 'regular ', color: '#363F38'},
  {brand, code: 'H29', name: 'Claret', type: 'regular ', color: '#B9395E'},
  {brand, code: 'H30', name: 'Burgundy', type: 'regular ', color: '#592F38'},
  {brand, code: 'H31', name: 'Turquoise', type: 'regular ', color: '#6797AE'},
  {brand, code: 'H32', name: 'Neon Pink', type: 'regular ', color: '#FF208D'},
  {brand, code: 'H33', name: 'Cerise', type: 'regular ', color: '#FF3956'},
  {brand, code: 'H34', name: 'Neon Yellow', type: 'transparent ', color: '#E5EF13'},
  {brand, code: 'H35', name: 'Neon Red', type: 'transparent ', color: '#FF2833'},
  {brand, code: 'H36', name: 'Neon Blue', type: 'transparent ', color: '#2353B0'},
  {brand, code: 'H37', name: 'Neon Green', type: 'transparent ', color: '#06B73C'},
  {brand, code: 'H38', name: 'Neon Orange', type: 'transparent ', color: '#FD8600'},
  {brand, code: 'H39', name: 'Fluorescent Yellow', type: 'regular ', color: '#F1F21C'},
  {brand, code: 'H40', name: 'Fluorescent Orange', type: 'regular ', color: '#FE630B'},
  {brand, code: 'H41', name: 'Fluorescent Blue', type: 'regular ', color: '#2659B2'},
  {brand, code: 'H42', name: 'Fluorescent Green', type: 'regular ', color: '#0CBD51'},
  {brand, code: 'H43', name: 'Pastel Yellow', type: 'regular ', color: '#F0EA37'},
  {brand, code: 'H44', name: 'Pastel Red', type: 'regular ', color: '#EE6972'},
  {brand, code: 'H45', name: 'Pastel Purple', type: 'regular ', color: '#886DB9'},
  {brand, code: 'H46', name: 'Pastel Blue', type: 'regular ', color: '#629ED7'},
  {brand, code: 'H47', name: 'Pastel Green', type: 'regular ', color: '#83CB70'},
  {brand, code: 'H48', name: 'Pastel Pink', type: 'regular ', color: '#CF70B7'},
  {brand, code: 'H49', name: 'Azure', type: 'regular ', color: '#4998BC'},
];

export {brand as hamaBrand, hamaBeads};
