import brands from '../brands';

const brand = brands.PERLER;
const perlerBeads = [
    { brand, code: 'P01', name: 'White', type: 'regular', color: '#f1f1f1' },
    { brand, code: 'P02', name: 'Cream', type: 'regular', color: '#e0dea9' },
    { brand, code: 'P03', name: 'Yellow', type: 'regular', color: '#ecd800' },
    { brand, code: 'P04', name: 'Orange', type: 'regular', color: '#ed6120' },
    { brand, code: 'P05', name: 'Red', type: 'regular', color: '#bf2e40' },
    { brand, code: 'P06', name: 'Bubblegum', type: 'regular', color: '#dd669b' },
    { brand, code: 'P07', name: 'Purple', type: 'regular', color: '#604089' },
    { brand, code: 'P08', name: 'Dark Blue', type: 'regular', color: '#2b3f87' },
    { brand, code: 'P09', name: 'Light Blue', type: 'regular', color: '#3370c0' },
    { brand, code: 'P10', name: 'Dark Green', type: 'regular', color: '#1c753e' },
    { brand, code: 'P11', name: 'Light Green', type: 'regular', color: '#56ba9f' },
    { brand, code: 'P12', name: 'Brown', type: 'regular', color: '#513931' },
    { brand, code: 'P17', name: 'Grey', type: 'regular', color: '#8a8d91' },
    { brand, code: 'P18', name: 'Black', type: 'regular', color: '#2e2f32' },
    { brand, code: 'P20', name: 'Rust', type: 'regular', color: '#8c372c' },
    { brand, code: 'P21', name: 'Light Brown', type: 'regular', color: '#815d34' },
    { brand, code: 'P33', name: 'Peach', type: 'regular', color: '#eebab2' },
    { brand, code: 'P35', name: 'Tan', type: 'regular', color: '#bc9371' },
    { brand, code: 'P38', name: 'Magenta', type: 'regular', color: '#f22a7b' },
    { brand, code: 'P47', name: 'Neon Yellow', type: 'transparent',  color: '#dce002' },
    { brand, code: 'P48', name: 'Neon Orange', type: 'transparent',  color: '#ff7700' },
    { brand, code: 'P49', name: 'Neon Green', type: 'transparent',  color: '#019e43' },
    { brand, code: 'P50', name: 'Neon Pink', type: 'transparent',  color: '#ff3991' },
    { brand, code: 'P52', name: 'Pastel Blue', type: 'regular', color: '#5390d1' },
    { brand, code: 'P53', name: 'Pastel Green', type: 'regular', color: '#76c882' },
    { brand, code: 'P54', name: 'Pastel Lavender', type: 'regular', color: '#8a72c1' },
    { brand, code: 'P56', name: 'Pastel Yellow', type: 'regular', color: '#fef875' },
    { brand, code: 'P57', name: 'Chedder', type: 'regular', color: '#f1aa0c' },
    { brand, code: 'P58', name: 'Toothpaste', type: 'regular', color: '#93c8d4' },
    { brand, code: 'P59', name: 'Hot Coral', type: 'regular', color: '#ff3851' },
    { brand, code: 'P60', name: 'Plum', type: 'regular', color: '#a24b9c' },
    { brand, code: 'P61', name: 'Kiwi Lime', type: 'regular', color: '#6cbe13' },
    { brand, code: 'P62', name: 'Cyan (aka Turquoise)', type: 'regular', color: '#2b89c6' },
    { brand, code: 'P63', name: 'Blush', type: 'regular', color: '#ff8285' },
    { brand, code: 'P70', name: 'Periwinkle Blue', type: 'regular', color: '#647cbe' },
    { brand, code: 'P75', name: 'Glow Green', type: 'glow',  color: '#bec696' },
    { brand, code: 'P79', name: 'Light Pink', type: 'regular', color: '#f6b3dd' },
    { brand, code: 'P80', name: 'Bright Green', type: 'regular', color: '#4fad42' },
    { brand, code: 'P81', name: 'Light Gray', type: 'regular', color: '#b1b5b2' },
    { brand, code: 'P??', name: 'Evergreen', type: 'regular', color: '#355343' },
    { brand, code: 'P82', name: 'Lavender', type: 'regular', color: '#ad98d4' },
    { brand, code: 'P83', name: 'Pink', type: 'regular', color: '#e44892' },
    { brand, code: 'P85', name: 'Gold', type: 'metal',  color: '#bb7634' },
    { brand, code: 'P88', name: 'Raspberry', type: 'regular', color: '#a53061' },
    { brand, code: 'P90', name: 'Butterscotch', type: 'regular', color: '#d48437' },
    { brand, code: 'P91', name: 'Parrot Green', type: 'regular', color: '#067c81' },
    { brand, code: 'P92', name: 'Dark Grey', type: 'regular', color: '#4d5156' },
    { brand, code: 'P93', name: 'Blueberry Cream', type: 'regular', color: '#8297d9' },
    { brand, code: 'P96', name: 'Cranapple', type: 'regular', color: '#803245' },
    { brand, code: 'P97', name: 'Prickly Pear', type: 'regular', color: '#bdda01' },
    { brand, code: 'P98', name: 'Sand', type: 'regular', color: '#e4b690' },
    { brand, code: 'P100', name: 'Pearl Coral', type: 'pearl', color: '#f97e79' },
    { brand, code: 'P101', name: 'Pearl Light Blue', type: 'pearl', color: '#7aaea2' },
    { brand, code: 'p102', name: 'Pearl Green', type: 'pearl', color: '#84b791' },
    { brand, code: 'P103', name: 'Pearl Yellow', type: 'pearl', color: '#cac033' },
    { brand, code: 'P104', name: 'Pearl Light Pink', type: 'pearl', color: '#d7a8a2' },
    { brand, code: 'P105', name: 'Silver', type: 'metal', color: '#777b81' }
];

export { brand as perlerBrand, perlerBeads };
